const data = {
    de: {
        "contact_nav": "Kontakt",
        "main_header": "Ferienwohnung in Sulingen",
        "details_header": "Ferienwohnung / Zimmer in Sulingen",
        "details_text": "Ferienwohnung für bis zu 4 Gäste · 2 Schlafzimmer · Badezimmer · Wohnzimmer · Küche",
        "description_header": "Inseratsbeschreibung",
        "description_text": "Von dieser zentral gelegenen Unterkunft aus seid ihr in Nullkommanichts an allen wichtigen Orten. Alles ist zu Fuß zu erreichen.",
        "apartment_header": "Deine Unterkunft",
        "apartment_text": "Die Wohnung besteht aus 3 Schlafzimmern, Wohnzimmer, Küche und Bad. 2 Schlafzimmer sind flexibel buchbar. Das 3. Zimmer ist für private Zwecke reserviert. Alle Zimmer befinden sich im 1. Stock und verfügen über eine Terrassentür auf die Balkone. Vor allen Fenstern und Türen sind Fliegengitter, die auch nachts die Mücken fern halten. Die Küche ist voll eingerichtet und bietet viel Platz auch zum Essen und Sitzen. Die beiden Schlafzimmer haben jeweils ein Doppelbett, Schreibtisch und TV mit Sat und Fire Stick. Prime und Disney+ können mit benutzt werden.",
        "price_header": "Preise",
        "price_room": "Übernachtung 40 – 80€ pro Nacht",
        "price_extra": "Endreinigung 40€ bei Einzelzimmer / 60€ bei ganzem Apartment incl. Wäschepaket",
        "contact_header": "Kontakt",
        "contact_text": "Meldet euch telefonisch oder per Mail. Wir sind für alle Fragen offen.",
        "equitment_header": "Ausstattung",
        "location_header": "Wegbeschreibung",
        "interaction_header": "Auch über Airbnb buchbar",
        "booking_choices": "Diese Möglichkeiten sind buchbar:",
        "booking_single": "1 Doppelzimmer mit gemeinsamer Nutzung Bad , Wohnzimmer, Küche und Balkone",
        "booking_all": "1 oder 2 Doppelzimmer mit alleiniger Nutzung aller anderen Räume.",
        "moon": "Abdunklung",
        "work": "Arbeitsplatz",
        "clothes": "Aufbewahrung von Kleidung",
        "baby": "Baby-Sicherheitsgitter",
        "bed": "Bettwäsche",
        "book": "Bücher und Lesematerial",
        "iron": "Bügeleisen",
        "shower": "Seife, Duschgel & Shampoo",
        "aid": "Erste-Hilfe-Set",
        "table_out": "Essbereich im Freien",
        "parking": "5 Parkplätze",
        "pillow": "Extrakissen und -decken",
        "fire": "Feuerlöscher",
        "hair": "Föhn",
        "freezer": "Gefrierschrank",
        "dishwasher": "Geschirrspülmaschine",
        "cooking": "Grundausstattung zum Kochen",
        "heater": "Heizung",
        "stove": "Herd",
        "chair": "Hochstuhl",
        "coffee": "Kaffeemaschine",
        "fridge": "Kühlschrank",
        "microwave": "Mikrowelle",
        "oven": "Ofen",
        "laudry": "Waschmaschine",
        "fire_alarm": "Rauchmelder",
        "kids_bed": "Reisebett für Kinder",
        "gaming": "Spielkonsole: Nintendo Wii",
        "balcony": "Terrasse oder Balkon",
        "toaster": "Toaster",
        "tv": "TV",
        "kettle": "Wasserkocher",
        "wine_glasses": "Weingläser",
        "wifi": "WLAN"

    },
    en: {
        "contact_nav": "Contact us",
        "main_header": "Holiday apartment in Sulingen",
        "details_header": "Holiday apartment / room in Sulingen",
        "details_text": "Apartment for up to 4 guests · 2 bedrooms · bathroom · livingroom · kitchen",
        "description_header": "Description",
        "description_text": "In the middle of Sulingen, but still quite rural. You can enjoy the tranquility or discover Sulingen in a few minutes.",
        "apartment_header": "The space",
        "apartment_text": "The apartment consists of 3 bedrooms, living room, kitchen and bathroom, which are shared. I rent 2 bedrooms, the 3 room is reserved for private purposes. Each room is can be booked individually. the apartment is on the 1st floor and and all rooms have a patio door onto the balconies. All the windows and doors are screens that keep the mosquitoes away even at night. and have a patio door onto the balconies. The kitchen is fully furnished and also offers plenty of space to eat and sit. Both bedrooms have queensize beds, tables to work at TV with satellite and fire stick. Prime and Disney+ can be used.",
        "price_header": "Pricing",
        "price_room": "40 – 80€ per night",
        "price_extra": "final cleaning 40€ for room / 80€ for apartment incl. laundry",
        "contact_header": "Contact us",
        "contact_text": "Reach out to us by mail or phone. Can ask us anything.",
        "equitment_header": "What this place offers",
        "location_header": "Location",
        "interaction_header": "Can also be booked over airbnb",
        "booking_choices": "These options are available for booking:",
        "booking_single": "1 double room with shared use of bathroom, living room, kitchen, and balconies.",
        "booking_all": "1 or 2 double rooms with exclusive use of all other rooms.",
        "moon": "Blackout curtains",
        "work": "Workspace",
        "clothes": "Clothing storage",
        "baby": "Baby safety gate",
        "bed": "Bedding",
        "book": "Books and reading material",
        "iron": "Iron",
        "shower": "Soap, shower gel & shampoo",
        "aid": "First aid kit",
        "table_out": "Outdoor dining area",
        "parking": "5 parking spaces",
        "pillow": "Extra pillows and blankets",
        "fire": "Fire extinguisher",
        "hair": "Hairdryer",
        "freezer": "Freezer",
        "dishwasher": "Dishwasher",
        "cooking": "Basic cooking equipment",
        "heater": "Heating",
        "stove": "Stove",
        "chair": "High chair",
        "coffee": "Coffee machine",
        "fridge": "Refrigerator",
        "microwave": "Microwave",
        "oven": "Oven",
        "laudry": "Washing machine",
        "fire_alarm": "Smoke detector",
        "kids_bed": "Travel crib for children",
        "gaming": "Game console: Nintendo Wii",
        "balcony": "Terrace or balcony",
        "toaster": "Toaster",
        "tv": "TV",
        "kettle": "Kettle",
        "wine_glasses": "Wine glasses",
        "wifi": "Wi-Fi"


    },
};

// const text = de;